uses: actions/checkout@v4
uses: Dylan700/sftp-upload-action@latest

with:
  server: 35.172.213.200 
  username: ubuntu
  key: ${{secrets.key}}
  passphrase: ${{secrets.passphrase}}
  port: 22
  uploads: |
    ./ => ./home/ubuntu/discord
